import BLACK_PICKER from '../img/colorPickers/BLACK.png';
import BROWN_PICKER from '../img/colorPickers/BROWN.png';
import CREAM_PICKER from '../img/colorPickers/CREAM.png';
import DARK_GREY_PICKER from '../img/colorPickers/DARK_GREY.png';
import LIGHT_GREY_PICKER from '../img/colorPickers/LIGHT_GREY.png';
import WHITE_PICKER from '../img/colorPickers/WHITE.png';
import SINUSOIDAL from '../img/sideBar/SINUSOIDAL.svg';
import TEJA from '../img/sideBar/TEJA.svg';
import TRAPEZOIDAL from '../img/sideBar/TRAPEZOIDAL.svg';
import MICRONERVADO from '../img/sideBar/MICRONERVADO.svg';
import S_ICON from '../img/icon/S_ICON.svg';
import DOWN_ARROW from '../img/icon/DOWN_ARROW.svg';
import TECHOS_SINUSOIDAL_BLACK from '../img/roofs/TECHOS_SINUSOIDAL_BLACK.png';
import TECHOS_SINUSOIDAL_BROWN from '../img/roofs/TECHOS_SINUSOIDAL_BROWN.png';
import TECHOS_SINUSOIDAL_CREAM from '../img/roofs/TECHOS_SINUSOIDAL_CREAM.png';
import TECHOS_SINUSOIDAL_DARK_GREY from '../img/roofs/TECHOS_SINUSOIDAL_DARK_GREY.png';
import TECHOS_SINUSOIDAL_LIGHT_GREY from '../img/roofs/TECHOS_SINUSOIDAL_LIGHT_GREY.png';
import TECHOS_SINUSOIDAL_WHITE from '../img/roofs/TECHOS_SINUSOIDAL_WHITE.png';
import TECHOS_SINUSOIDAL_DEFAULT from '../img/roofs/TECHOS_SINUSOIDAL_CREAM.png';
import TECHOS_TRAPEZOIDAL_BLACK from '../img/roofs/TECHOS_TRAPEZOIDAL_BLACK.png';
import TECHOS_TRAPEZOIDAL_BROWN from '../img/roofs/TECHOS_TRAPEZOIDAL_BROWN.png';
import TECHOS_TRAPEZOIDAL_CREAM from '../img/roofs/TECHOS_TRAPEZOIDAL_CREAM.png';
import TECHOS_TRAPEZOIDAL_DARK_GREY from '../img/roofs/TECHOS_TRAPEZOIDAL_DARK_GREY.png';
import TECHOS_TRAPEZOIDAL_LIGHT_GREY from '../img/roofs/TECHOS_TRAPEZOIDAL_LIGHT_GREY.png';
import TECHOS_TRAPEZOIDAL_WHITE from '../img/roofs/TECHOS_TRAPEZOIDAL_WHITE.png';
import TECHOS_TRAPEZOIDAL_DEFAULT from '../img/roofs/TECHOS_TRAPEZOIDAL_CREAM.png';
import TECHOS_TEJA_BROWN from '../img/roofs/TECHOS_TEJA_BROWN.png';
import TECHOS_TEJA_BLACK from '../img/roofs/TECHOS_TEJA_BLACK.png';
import TECHOS_TEJA_DEFAULT from '../img/roofs/TECHOS_TEJA_BROWN.png';
import PAREDES_MICRONERVADO_BLACK from '../img/roofs/PAREDES_MICRONERVADO_BLACK.png';
import PAREDES_MICRONERVADO_CREAM from '../img/roofs/PAREDES_MICRONERVADO_CREAM.png';
import PAREDES_MICRONERVADO_DARK_GREY from '../img/roofs/PAREDES_MICRONERVADO_DARK_GREY.png';
import PAREDES_MICRONERVADO_LIGHT_GREY from '../img/roofs/PAREDES_MICRONERVADO_LIGHT_GREY.png';
import PAREDES_MICRONERVADO_WHITE from '../img/roofs/PAREDES_MICRONERVADO_WHITE.png';
import PAREDES_MICRONERVADO_DEFAULT from '../img/roofs/PAREDES_MICRONERVADO_CREAM.png';

export const PICKERS = {
  BLACK_PICKER,
  BROWN_PICKER,
  CREAM_PICKER,
  DARK_GREY_PICKER,
  LIGHT_GREY_PICKER,
  WHITE_PICKER,
};

export const SIDE_BAR_ICON = {
  SINUSOIDAL,
  TEJA,
  TRAPEZOIDAL,
  MICRONERVADO,
};

export const ICON = {
  S_ICON,
  DOWN_ARROW,
};

export const CENTRAL_IMAGE = {
  TECHOS_SINUSOIDAL_BLACK,
  TECHOS_SINUSOIDAL_BROWN,
  TECHOS_SINUSOIDAL_CREAM,
  TECHOS_SINUSOIDAL_DARK_GREY,
  TECHOS_SINUSOIDAL_LIGHT_GREY,
  TECHOS_SINUSOIDAL_WHITE,
  TECHOS_SINUSOIDAL_DEFAULT,
  TECHOS_TRAPEZOIDAL_BLACK,
  TECHOS_TRAPEZOIDAL_BROWN,
  TECHOS_TRAPEZOIDAL_CREAM,
  TECHOS_TRAPEZOIDAL_DARK_GREY,
  TECHOS_TRAPEZOIDAL_LIGHT_GREY,
  TECHOS_TRAPEZOIDAL_WHITE,
  TECHOS_TRAPEZOIDAL_DEFAULT,
  TECHOS_TEJA_BROWN,
  TECHOS_TEJA_BLACK,
  TECHOS_TEJA_DEFAULT,
  PAREDES_MICRONERVADO_BLACK,
  PAREDES_MICRONERVADO_CREAM,
  PAREDES_MICRONERVADO_DARK_GREY,
  PAREDES_MICRONERVADO_LIGHT_GREY,
  PAREDES_MICRONERVADO_WHITE,
  PAREDES_MICRONERVADO_DEFAULT,
};
